# CI/PR Pipeline that deploys an ARM template to create or update the resources needed by the other pipelines.
trigger:
  branches:
    include:
      - adf_publish
  paths:
    include:
      - schemaCustomerADF/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - schemaCustomerADF/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: devopsforadf-dev-vg
  - name: WORKSPACE_SKU # https://docs.microsoft.com/en-us/azure/machine-learning/overview-what-is-azure-ml#sku
    value: basic

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(AZURE_RM_SVC_CONNECTION)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: "$(Build.SourcesDirectory)/schemaCustomerADF/ARMTemplateForFactory.json"
      deploymentMode: "Incremental"
    displayName: "Deploy DataOps resources to Azure"
